[package]
name = "slowrm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slowrm_lib = {path = "../slowrm_lib"}